- name: "Create /root/.ssh"
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: "Ensure /root/.ssh/authorized_keys exists"
  command: install -m 0600 /dev/null /root/.ssh/authorized_keys
  args:
    creates: /root/.ssh/authorized_keys

- name: "Install rsync validation script"
  copy:
    src=validate-rsync-backup
    dest=/root/validate-rsync-backup
    owner=root
    group=root
    mode=0755

- name: "Add backup.infra rsa key"
  lineinfile:
    destfile: /root/.ssh/authorized_keys
    regexp: 'root@backup.infra.ring.nlnog.net'
    line: 'from="109.72.93.35,2a00:f10:122::35",command="/root/validate-rsync-backup" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9zR9lQ7mr8aWhAzJBUhbTCg6RaMR0aSIpafvXjNiCzZg1yO+QOkw8N8i0lwyxND5xHiT4pgaL4ILqJ7SefocIU9MgcY77YUFHzkpOFjGpSF8I0nY4Q0WlYC0XFJvO4hx7sUXFBQze55Xbe4OBEEJoKCBbfCXEwgiPobXrcKSoCjT49hcz4F3q5MxEHgu1wvXzG7eiOyCtsNW5T/I5vImt0usP7SKGBBnWLZY92pfbtmqDwZ1q1joaM/qADO0E1YiXTL8QTtuhG5PMC8khAjZ9AzljaMi9UX1vjKWG7DL6VVSTv6nI1GNLABg8/Cwq69Dujho6zezWOANega6mEhzh root@backup.infra.ring.nlnog.net'

- name: "Add storage01.infra rsa key"
  lineinfile:
    destfile: /root/.ssh/authorized_keys
    regexp: 'root@storage01.infra.ring.nlnog.net'
    line: 'from="35.174.70.43,2600:1f18:415a:7301::102",command="/root/validate-rsync-backup" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOaWLVcbWGzMgFggF8rkHGKt4kGByrE1c1bAz+kMBaVoqrgfO55e18xGzCUDhTE3bzfNBUXwMa23XDn4LfcZJfa+5Qj8BlvUJhS6b2fejv0xdgvhTda7r6pV+Mxqy0jRP1uoKaoUJ3M27bWMbEGbvrC3Up5eyacGs1LeJu/Aaa28xjT9bah4FjQXf/j45Vd3yrFjBOblEhKgsbgWvu5Ptga7UQ5HBmkZ1nhaFfwHQngjYDYu7Z5g8nWXrii/hyi/tsYAL6iH7quv82F+foZgbF9nsVglF736g5nu4TtGLZ2HpsoEoqfRKj1GW1yHZWvlvL+IZHuNc2t+WpbLLIfDWmcDd4TLAdsfuH5eNSrA0VpeuHHn/Ng+sqPAtJyd7p7SlD7c2sueqM2OjgZt2g//acWDB5qTA+hnIS0nz409OGsfuyoU6VSkfSAu5RJ+sgJVH4aY0XJegz7HqmKTYLXxiPvmTgyElZak4Fm2s/fqv4LxnZFlnap9o0J1CUrlg/Ak8= root@storage01.infra.ring.nlnog.net'

