- name: "Install apache2"
  apt: name={{ item }} state=latest
  with_items:
    - apache2

- name: "Install WSGI for python2"
  apt: name={{ item }} state=latest
  with_items:
    - libapache2-mod-wsgi
  when: ansible_distribution_release == "bionic" and need_wsgi_py3|default(None) != True

- name: "Install WSGI for python3"
  apt: name={{ item }} state=latest
  with_items:
    - libapache2-mod-wsgi-py3
  when: need_wsgi_py3|default(None) == True

- name: "Install php when required"
  apt: name={{ item }} state=latest
  with_items:
    - libapache2-mod-php7.2
    - php7.2-mbstring
    - php7.2-mysql
  when: need_php|default(None) == true
  notify: restart apache2

- name: "Remove apache2 placeholder site"
  file:
    path: /etc/apache2/sites-enabled/000-default
    state: absent

- name: "Enable apache2 modules (1)"
  file:
    src: /etc/apache2/mods-available/{{ item }}.load
    dest: /etc/apache2/mods-enabled/{{ item }}.load
    state: link
  with_items:
    - headers
    - ssl
    - socache_shmcb
    - cgid
    - rewrite
  notify: restart apache2

- name: "Enable apache2 modules (2)"
  file:
    src: /etc/apache2/mods-available/{{ item }}.conf
    dest: /etc/apache2/mods-enabled/{{ item }}.conf
    state: link
  with_items:
    - ssl
    - cgid
  notify: restart apache2

- name: "Install apache2 main config"
  copy:
    src="apache2.conf"
    dest="/etc/apache2/apache2.conf"
    owner=root
    group=root
    mode=0644
  notify: restart apache2

- name: "Install wsgi daemon config"
  copy:
    src="wsgi_daemons.conf"
    dest="/etc/apache2/wsgi_daemons.conf"
    owner=root
    group=root
    mode=0644
  notify: restart apache2

- name: "Create vhost directories"
  file:
    path: "/var/www/{{ item }}.ring.nlnog.net"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ apache_vhosts|default([]) }}"

- name: "Install vhosts"
  copy:
    src="{{ item }}-vhost.conf"
    dest="/etc/apache2/sites-available/{{ item }}.ring.nlnog.net"
    owner=root
    group=root
    mode=0644
  with_items: "{{ apache_vhosts|default([]) }}"
  notify: restart apache2

- name: "Enable vhosts"
  file:
    src: "/etc/apache2/sites-available/{{ item }}.ring.nlnog.net"
    dest: "/etc/apache2/sites-enabled/{{ item }}.ring.nlnog.net.conf"
    owner: root
    group: root
    state: link
  with_items: "{{ apache_vhosts|default([]) }}"
  notify: restart apache2

- name: "Start apache2"
  service: name=apache2 state=started

