- name: "Install library dependencies"
  apt: name={{ item }} state=latest
  with_items:
    - libdpkg-perl
    - libgetopt-simple-perl
    - purgekernels

- name: "Install purgekernels apt.conf"
  copy:
    src=88purgekernels
    dest=/etc/apt/apt.conf.d/88purgekernels
    owner=root
    group=root
    mode=0755

- name: "Install ring-fetch-nodes-json"
  copy:
    src=ring-fetch-nodes-json
    dest=/usr/local/bin/ring-fetch-nodes-json
    owner=root
    group=root
    mode=0755

- name: "Add jsonlint symlink"
  file:
    src: /usr/bin/jsonlint-py
    dest: /usr/bin/jsonlint
    owner: root
    group: root
    state: link
  when: ansible_distribution_release == "bionic"

- name: Add cronjob for ring-fetch-nodes-json
  template:
    src: "cron.d/ring-fetch-nodes-json.j2"
    dest: /etc/cron.d/ring-fetch-nodes-json

- name: "Install geotrshell"
  copy:
    src=geotrshell
    dest=/usr/local/bin/geotrshell
    owner=root
    group=root
    mode=0755

- name: "Install intraceshell"
  copy:
    src=intraceshell
    dest=/usr/local/bin/intraceshell
    owner=root
    group=root
    mode=0755

- include: dbmaster.yml
  when: dbmaster == true

- include: pdnsmaster.yml
  when: pdnsmaster == true

