- name: "Install deb prerequisites for ripe-atlas-tools"
  apt: name={{ item }} state=present
  with_items:
    - libffi-dev
    - libssl-dev
    - virtualenv

- name: "Install deb prerequisites for ripe-atlas-tools (jammy)"
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - python3-virtualenv
    - python3-pip
  when: ansible_distribution_release == "jammy"

- name: "Install ripe-atlas-tools (jammy)"
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ ripe_atlas_venv_dir }}"
    virtualenv_python: python3
  with_items:
    - IPy
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
    - 'git+https://github.com/RIPE-NCC/ripe-atlas-tools@latest#egg=ripe-atlas-tools'
  when: ansible_distribution_release == "jammy"

- name: "Create symlinks for ripe-atlas-tools"
  file:
    state: link
    force: true
    src: "{{ ripe_atlas_venv_dir }}/bin/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
  with_items:
    - adig
    - ahttp
    - antp
    - aping
    - asslcert
    - atraceroute
    - ndg_httpclient
    - ripe-atlas
    - wsdump.py
