- name: create syslog-ng.conf
  template:
    src: etc/syslog-ng/syslog-ng.conf.client
    dest: /etc/syslog-ng/syslog-ng.conf
    owner: root
    group: root
    mode: 0644
  notify: syslog restart service

- name: check for /etc/network/if-up.d
  stat:
    path: /etc/network/if-up.d
  register: network_ifupd

- name: install if-up.d script on ringnodes
  copy:
    src=if-up.d/syslog-ng
    dest=/etc/network/if-up.d/syslog-ng
    owner=root
    group=root
    mode=0755
  when: "'ringnode' in group_names and network_ifupd.stat.exists"
