---
software:
  all:
    - apache2-utils
    - bash-completion
    - bc
    - bind9-host
    - bison
    - build-essential
    - bzr
    - command-not-found
    - curl
    - cvs
    - datamash
    - dnsutils
    - dsniff
    - flex
    - fpdns
    - fping
    - gnupg
    - gnutls-bin
    - graphviz
    - hping3
    - htop
    - httping
    - iotop
    - ipcalc
    - iperf
    - iputils-ping
    - iputils-tracepath
    - jq
    - landscape-common
    - language-pack-en-base
    - ldnsutils
    - lft
    - lftp
    - libcache-cache-perl
    - libsqlite3-dev
    - libxml2-dev
    - lsof
    - ltrace
    - lynx
    - man-db
    - markdown
    - members
    - mercurial
    - moreutils
    - mtr-tiny
    - nano
    - ndisc6
    - netcat-openbsd
    - netsed
    - net-tools
    - ngrep
    - nmap
    - pastebinit
    - psmisc
    - pv
    - python3-requests
    - rsync
    - ruby
    - screen
    - sipcalc
    - snmp
    - socat
    - strace
    - sysstat
    - tcpdump
    - tcptraceroute
    - telnet
    - tmux
    - traceroute
    - tshark
    - ucspi-tcp
    - unattended-upgrades
    - unbound-host
    - update-manager-core
    - update-notifier-common
    - vim
    - virt-what
    - w3m
    - wget
    - whois
    - swaks
    - ruby-json
    - libldns-dev
    - cmake
  bionic:
    - git
    - jsonlint
    - iperf3
    - ruby-dev
    - parallel
    - python3-pip
    - dnsviz
    - php7.2-cli
    - dnsdiag
    - python
    - python-beautifulsoup
    - python-demjson
    - python-dnspython
    - python-flask
    - python-ipaddr
    - python-libxml2
    - python-mysqldb
    - python-networkx
    - python-pip
    - python-pycountry
    - python-setuptools
    - python-simplejson
    - python-virtualenv
    - sshfp
    - python3-dev
  jammy:
    - python3
    - python3-demjson
    - python3-pycountry
    - git
    - jsonlint
    - iperf3
    - ruby-dev
    - parallel
    - python3-pip
    - dnsviz
    - dnsdiag
    - python3-dev
