- name: "Install required packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - zfsutils-linux

- name: "Create backup mountpoint"
  file:
    path: /backups
    state: directory
    owner: root
    group: root
    mode: 0755
  register: backup_mountpoint

- name: "Create zfs base"
  shell: |
    /usr/sbin/zfs create tank/backups
    /usr/sbin/zfs set mountpoint=/backups tank/backups
  when: backup_mountpoint.changed

- name: "Populate backup-hosts file"
  template:
    src: backup-hosts.j2
    dest: "/backups/backup-hosts"
    owner: root
    group: root
    mode: 0644

- name: "Install backup scripts"
  copy:
    src={{ item }}
    dest=/usr/local/sbin/{{ item }}
    owner=root
    group=root
    mode=0744
  with_items:
    - start-backup
    - zrbackup
    - zfs_health_check
    - check-backup-age

- name: "Install systemd service"
  copy:
    src=systemd/zrbackup.service
    dest=/etc/systemd/system/zrbackup.service
  register: zrbackup_systemd

- name: "Reload systemd"
  shell: /usr/bin/systemctl daemon-reload
  notify: restart zrbackup
  when: zrbackup_systemd.changed

- name: "Start zrbackup service"
  service: name=zrbackup state=started enabled=yes

- name: "Install backup age check cronjob"
  copy:
    src=cron.d/ring_backup
    dest=/etc/cron.d/ring_backup
